### PR TITLE
migrating to composer for dependency management #1

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by radius314** [comment]
We should rename this repo to bmlt-wordpress-satellite-plugin to match the folder name in SVN and how it's deployed in wp-plugins.

Additionally, PR this requires two other pull requests get merged:

https://bitbucket.org/bmlt/bmlt-satellite-driver/pull-requests/1/adding-composer-file/diff
https://bitbucket.org/bmlt/bmlt-satellite-base-class/pull-requests/1/moving-to-composer/diff

**Comment by radius314** [comment]
We need to transfer this repo to bmlt-enabled org.

**Comment by radius314** [comment]
Also can you make me a contributor on the wordpress plugin?

**Comment by LittleGreenViper** [comment]
I can't. You are already a committer. I suspect that you will automatically become a contributor, once you make a commit on the SVN.

**Comment by LittleGreenViper** [comment]
I did make you and Patrick support reps.

**Comment by radius314** [comment]
Need to be an admin to transfer ownership unless you do it.

**Comment by LittleGreenViper** [comment]
I'm not exactly sure how to transfer. I'll find out...

**Comment by radius314** [comment]
Under settings, scroll way to the bottom in the danger zone.

**Comment by LittleGreenViper** [comment]
Oh, you mean the GitHub repo; not the WP repo. Gimme a minute...

**Comment by radius314** [comment]
Yup.  For the Wordpress plugin, you need to go into advanced view and add
“radius314” as a contributor.

**Comment by LittleGreenViper** [comment]
Got it. You and Patrick are already committers (It doesn't seem to let you add "contributors". Might be a calculated property, based on you having made SVN commits).

I transferred a few BMLT repos to bmlt-enabled.

**Comment by radius314** [comment]
Thanks

**Comment by LittleGreenViper** [comment]
Thank YOU.

**Pull request merged**
